### ISSUE TITLE
docker compose MySQL container [2002] Connection refused

### ISSUE THREAD

**Issue by lydia-gu** [usydtechlab/etaki3d#2]
Cannot connect to mysql container from fpm-alpine container, docker compose MySQL container [2002] Connection refused

Solution:
- https://github.com/docker-library/php/issues/320#issuecomment-256463379
- https://stackoverflow.com/questions/50325230/docker-compose-mysql-container-2002-connection-refused

**Comment by lydia-gu** [comment]
Fixed by: fea8bd6bd8c87266ad21831c17c267e41130513c & ac95750b7678128d759eddb1cf92f5328269d6d6

**Comment by GabrielPCS** [comment]
En la terminal inspecciona la ip del contenedor de la base de datos:

docker inspect [db_caontainer] | grep IPAddress

usas la ip que te arroje como $dbhost
